version: "3.9"

services:
  client:
    build:
      context: https://shrangit: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@github.com/BotnBolt-Admin/fixitai-client.git#staging
    container_name: fixitai-client
    ports:
      - "3000:3000"
    restart: always

  server:
    build:
      context: https://shrangit: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@github.com/BotnBolt-Admin/fixitai-server.git#staging
    container_name: fixitai-server
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: fixitai-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fixitai
      MYSQL_USER: fixitai
      MYSQL_PASSWORD: fixitai123
    ports:
      - "3306:3306"
    restart: always
